config/routes.rb
Rails.application.routes.draw do
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  serialize :recurring, Hash

  def recurring=(value)
    if RecurringSelect.is_valid_rule?(value)
      super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
      super(nil)
    end
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)
    schedule
  end

  def calendar_events(start)
    if recurring.empty?
      [self]
    else
      #start_date = start.beginning_of_month.beginning_of_week
      end_date = start.end_of_month.end_of_week
      schedule(start_time).occurrences(end_date).map do |date|
        Event.new(id: id, name: name, start_time: date)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @calendar_events = []
    if @events.any?
      start = params.fetch(:start_time, Time.zone.now).to_date
      @calendar_events = @events.flat_map{ |e| e.calendar_events(start) }
    end
    respond_to do |format|
      format.html { render 'events/index' }
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    Rails.logger.error "CALLING DESTROY FOR EVENT #{@event.inspect}"
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :start_time, :recurring)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<div data-controller="event">
<%= form_with model: event do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :recurring %>
    <%= f.select_recurring :recurring, nil, allow_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

<script>
    document.addEventListener('ready', function () {
        //document.querySelectorAll('form').forEach(function (el) {
        //    el.dataset.turbo = false
        //})
        $("#event_recurring").on("change", function() {
            alert("This is actually firing!");
            return $(this).recurring_select('changed');
        });
        var elem = document.getElementById("event_recurring");
        console.error("elem: ", elem);
        $("#event_recurring").change(function() {
            alert( "Handler for .change() called." );
        });
    });
</script>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= month_calendar events: @calendar_events do |day, events| %>
  <div><strong><%= day.to_s %></strong></div>
  <% events.each do |event| %>
    <div>
      <%= link_to event.name, event_path(event.id) %>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Start time</th>
    <th>Recurring</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.start_time %></td>
      <td><%= event.recurring %></td>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>Recurring:</strong>
  <%= @event.recurring %>
</p>

<p>
  <%= button_to "Delete", @event, method: :delete %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventScheduling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="script" href="recurring_select/index.js" data-turbo-track="reload">
  </head>

  <body>
    <%= yield %>
  </body>
</html>